version: 2
updates:
  - package-ecosystem: github-actions    #패키지 에코시스템
    directory: /                         #패키지 매니패스트 위치
    schedule:                            #업데이트 스케줄
      interval: daily                    #업데이트 간격