name: Auto patch merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actior == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - id: meta                             # 의존성 메타데이터 가져오기
        uses: dependabot/fetch-metadata@v3   # 조건 분기로 버전 업데이트인지 확인
      - if: ${{ steps.meta.outputs.update_type == 'version-update:semver-patch' }}
        run: | 
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto